# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: required
dist: trusty

before_install:
  - unset _JAVA_OPTIONS

before_script:
  - export MAVEN_SKIP_RC=true

before_cache:
  - rm -rf $HOME/.m2/repository/org/locationtech/geomesa

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

script:
  - export MAVEN_OPTS="-Xmx1g -Djava.net.preferIPv4Stack=true"
  - ./.travisbuild.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/073f83aefca36a4e0118
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
